# $Id: Makefile,v 1.1 2008/06/17 08:08:29 casse Exp $
include ../Makefile.head

SOURCES = \
	irg.ml \
	sem.ml \
	lexer.mll \
	parser.mly \
	main.ml

$(eval $(call ocaml_prog,irg,$(SOURCES)))

include ../Makefile.tail
