/* Generated by gep ($(date)) copyright (c) 2008 IRIT - UPS */

#include <stdlib.h>
#include <stdio.h>
/* #include <math.h>  needed for affiche_valeur_binaire (which is not well coded) */

#include "fetch.h"
#include "decode.h" /* api.h will be in it, for fetch functions, decode_table.h also */
#include "config.h" /* for memory endiannesses */

#define gliss_error(e) fprintf(stderr, (e))


/* Fonctions Principales */

void gliss_execute(gliss_state_t *state, gliss_inst_t *inst)
{
	gliss_code_table[inst->ident](inst);
}


/* End of file gliss_code.c */
