/* Generated by gep ($(date)) copyright (c) 2008 IRIT - UPS */

#include <stdlib.h>
#include <stdio.h>
/* #include <math.h>  needed for affiche_valeur_binaire (which is not well coded) */

#include "fetch.h"
#include "decode.h" /* api.h will be in it, for fetch functions, decode_table.h also */
#include "config.h" /* for memory endiannesses */
#include "code.h"

#define gliss_error(e) fprintf(stderr, (e))

#include "code_table.h"

/**
 * Execute the given instruction in the given state.
 * @param state		Current execution state.
 * @param inst		Current instruction to execute.
 */
void gliss_execute(gliss_state_t *state, gliss_inst_t *inst)
{
	gliss_code_table[inst->ident](state, inst);
}


/* End of file gliss_code.c */
