/* Generated by gep ($(date)) copyright (c) 2008 IRIT - UPS */

#ifndef GLISS_GLISS_INCLUDE_GLISS_DECODE_H	/* Caution: all GLISS_ occurrence will be renamed, the 1rst shouldn't */
#define GLISS_GLISS_INCLUDE_GLISS_DECODE_H


#if defined(__cplusplus)
extern  "C"
{
#endif


#define GLISS_DECODE_STATE
#define GLISS_DECODE_INIT(s)
#define GLISS_DECODE_DESTROY(s)

#if defined(__cplusplus)
}
#endif

#endif /* GLISS_GLISS_INCLUDE_GLISS_DECODE_H */
