/* Generated by gep ($(date)) copyright (c) 2008 IRIT - UPS */

#ifndef GLISS_GLISS_INCLUDE_GLISS_FETCH_H	/* Caution: all GLISS_ occurrence will be renamed, the 1rst shouldn't */
#define GLISS_GLISS_INCLUDE_GLISS_FETCH_H


#if defined(__cplusplus)
extern  "C"
{
#endif

#include "../include/ppc/api.h"
#include "mem.h" /* if mem function definitions not in api (even as an include), else: remove this line */
#include "fetch_table.h" /* or ../include/gliss/ ? */

/*void GLISS_init_fetch(void); // IDEE: rajouter un param state_t, permet d'accéder à la mémoire pour lire et trouver l'ID d'une instruction
void GLISS_halt_fetch(void);

GLISS_ident_t *GLISS_fetch(GLISS_state_t *state, GLISS_address_t addr,
GLISS_code_t *code)*/

/*ça sert encore à qqchose maintenant ?
void GLISS_free_inst(GLISS_inst_t *instr);*/

/* fetching */
/*
prototypes from api.h
gliss_fetch_t *gliss_new_fetch(gliss_platform_t *state);
void gliss_delete_fetch(gliss_fetch_t *fetch);
int gliss_fetch(gliss_fetch_t *fetch, gliss_address_t address); */


#if defined(__cplusplus)
}
#endif

#endif /* GLISS_GLISS_INCLUDE_GLISS_FETCH_H */
