/* Generated by gep ($(date)) copyright (c) 2008 IRIT - UPS */

#ifndef GLISS_GLISS_INCLUDE_GLISS_FETCH_H	/* Caution: all GLISS_ occurrence will be renamed, the 1rst shouldn't */
#define GLISS_GLISS_INCLUDE_GLISS_FETCH_H


#if defined(__cplusplus)
extern  "C"
{
#endif

#include "../include/gliss/api.h"
#include "../include/gliss/mem.h" /* if mem function definitions not in api (even as an include), else: remove this line */
#include "fetch_table.h" /* or ../include/gliss/ ? */


#define GLISS_FETCH_STATE
#define GLISS_FETCH_INIT(s)
#define GLISS_FETCH_DESTROY(s)

#if defined(__cplusplus)
}
#endif

#endif /* GLISS_GLISS_INCLUDE_GLISS_FETCH_H */
