/* Generated by gep ($(date)) copyright (c) 2011 IRIT - UPS */

#include <assert.h>
#include <$(proc)/debug.h>
#include <$(proc)/macros.h>

#define GLISS_I		r.iv
#define GLISS_L		r.lv
#define GLISS_F		r.fv
#define GLISS_D		r.dv

static register_bank_t $(proc)_registers[] = {
$(foreach registers)$(if is_debug)
	{
		$(id),
		"$(label)",
		$(format),
		$(size),
		$(if is_pc)RTYPE_ADDR$(else)$(if is_float)RTYPE_FLOAT$(else)RTYPE_INT$(end)$(end),
		$(type_size)
	},
$(end)$(end)	{
		-1
	}
};


/**
 * Get the description of registers of the architecture.
 * @return		Array of registers (last one has a negative identifier).
 */
register_bank_t *$(proc)_get_registers(void) {
	return $(proc)_registers;
}

/**
 * Get the value of a register.
 * @param state		Current state.
 * @param id		Register identifier (from register_bank_t).
 * @param idx		Index in the bank (ignored for non-mutiple register bank).
 * @return			Value of the register.
 */
register_value_t $(proc)_get_register($(proc)_state_t *state, int id, int idx) {
	register_value_t r;
	switch(id) {
$(foreach registers)$(if is_debug)
	case $(id):
		$(get)
		break;
$(end)$(end)
	default:
		assert(0);
	}
	return r;
}


/**
 * Set the value of a register in the given state.
 * @param state		Current state.
 * @param id		Register identifier (from register_bank_t).
 * @param idx		Index in the bank (ignored for non-mutiple register bank).
 * @param value		Value to put in register.
 */
void $(proc)_set_register($(proc)_state_t *state, int id, int idx, register_value_t r) {
	switch(id) {
$(foreach registers)$(if is_debug)
	case $(id):
		$(set)
		break;
$(end)$(end)
	default:
		assert(0);
	}
}
