/* Generated by gep ($(date)) copyright (c) 2008 IRIT - UPS */

#include <string.h>
#include <stdio.h>
#include "../include/$(proc)/api.h"
#include "../include/$(proc)/id.h"
#include "../include/$(proc)/macros.h"
#include "grt.h"

typedef void (*disasm_t)(char *buffer, $(proc)_inst_t *inst);


/* functions */
static void disasm_unknown(char *buffer, $(proc)_inst_t *inst) {
	strcpy(buffer, "<unknown>");
}

$(foreach instructions)
static void disasm_$(IDENT)(char *__buffer, $(proc)_inst_t *inst) {
	$(disassemble)
}
$(end)

/* table */
static disasm_t disasm_tab[] = {
	disasm_unknown$(foreach instructions),
	disasm_$(IDENT)$(end)
};

/**
 * Disassemble the given instruction.
 * @param buffer	Buffer to write in.
 * @param inst		Decode instruction.
 */
void $(proc)_disasm(char *buffer, $(proc)_inst_t *inst) {
	disasm_tab[inst->ident](buffer, inst);
}
