/* Generated by gep ($(date)) copyright (c) 2008 IRIT - UPS */

#ifndef GLISS_$(PROC)_INCLUDE_$(PROC)_FETCH_TABLE_H
#define GLISS_$(PROC)_INCLUDE_$(PROC)_FETCH_TABLE_H


#if defined(__cplusplus)
extern  "C"
{
#endif

#include <$(proc)/id.h>
#include <$(proc)/gen_int.h>


/* data structures */

typedef enum
{
   INSTRUCTION,
   TABLEFETCH
} Type_Decode;

typedef struct
{
	Type_Decode type;
	void *ptr;	/* will be used to store an instruction ID or the address of a Table_Decodage */
} Decode_Ent;


$(INIT_FETCH_TABLES)


#if defined(__cplusplus)
}
#endif

#endif /* GLISS_$(PROC)_INCLUDE_$(PROC)_FETCH_TABLE_H */
