/* Generated by $(version) ($(date)) */
#ifndef $(PROC)_PLATFORM_H
#define $(PROC)_PLATFGORM_H

#include "../include/$(proc)/api.h"
$(foreach modules)
$(if is_mem)
#include "../include/$(proc)/mem.h"
$(else)
#include "$(name).h"
$(end)
$(end)

/* $(proc)_platform_t structure */
struct $(proc)_platform_t {
	int usage;
	union {
		$(proc)_memory_t *array[0];
		struct {
$(foreach memories)
			$(proc)_memory_t *$(name);
$(end)
		} named;
	} mems;
$(foreach modules)
	$(PROC)_$(NAME)_STATE
$(end)
};

/* functions */

#endif	/* $(PROC)_PLATFORM_H */
